# Generated by Django 3.1.7 on 2021-02-23 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=255)),
                ('year', models.DateField()),
                ('set', models.IntegerField()),
                ('conducting_authority', models.TextField(blank=True)),
                ('number_of_applicants', models.IntegerField(blank=True, null=True)),
                ('applicants_present', models.IntegerField(blank=True, null=True)),
                ('recommended_answer_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recommended_for_exam', to='analytics.answerkey')),
            ],
            options={
                'unique_together': {('branch', 'year', 'set')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('image', models.URLField()),
                ('gateoverflow_link', models.URLField()),
                ('type', models.IntegerField(choices=[(0, 'Mcq'), (1, 'Msq'), (2, 'Nat')], db_index=True)),
                ('answer_choices', models.JSONField()),
                ('max_marks', models.FloatField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=255)),
                ('candidate_name', models.CharField(max_length=255)),
                ('test_center_name', models.CharField(max_length=255)),
                ('test_date', models.DateField()),
                ('test_time_start', models.DateTimeField()),
                ('test_time_end', models.DateTimeField()),
                ('submission_url', models.URLField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.submission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted', models.IntegerField()),
                ('positive_marks', models.FloatField()),
                ('negative_marks', models.FloatField()),
                ('net_marks', models.FloatField()),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.answerkey')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.submission')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='evaluations',
            field=models.ManyToManyField(through='analytics.SubmissionEvaluation', to='analytics.AnswerKey'),
        ),
        migrations.AddField(
            model_name='submission',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.exam'),
        ),
        migrations.AddField(
            model_name='submission',
            name='items',
            field=models.ManyToManyField(through='analytics.SubmissionItem', to='analytics.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, to='analytics.Topic'),
        ),
        migrations.CreateModel(
            name='AnswerKeyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.TextField()),
                ('marks_to_all', models.BooleanField(default=False)),
                ('excluded', models.BooleanField(default=False)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.answerkey')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.question')),
            ],
        ),
        migrations.AddField(
            model_name='answerkey',
            name='answers',
            field=models.ManyToManyField(through='analytics.AnswerKeyItem', to='analytics.Question'),
        ),
        migrations.AddField(
            model_name='answerkey',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.exam'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('exam', 'candidate_id')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('exam', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='answerkey',
            unique_together={('exam', 'name')},
        ),
    ]
